spring.application.name=tree_project_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/rahemDB
spring.datasource.username=postgres
spring.datasource.password=4444
spring.jpa.hibernate.ddl-auto=update


jwt.expiration=1000